### ISSUE TITLE
启动失败了

### ISSUE THREAD

**Issue by CainLuo** [Genshin-bots/gsuid_core#54]
按照文档来配置, 然后使用 poetry 或者 pdm 启动都不行, 下面是错误代码:

```shell
02-26 15:59:51 [INFO] gsuid_core.server | [GsCore] 开始加载插件... 
02-26 15:59:52 [SUCCESS] gsuid_core.server | 插件gs_test导入成功! 
02-26 15:59:52 [SUCCESS] gsuid_core.server | 插件.DS_Store导入成功! 
02-26 15:59:52 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_resource | [资源文件下载] 正在检查与下载缺失的资源文件，可能需要较长时间，请稍等 
02-26 15:59:52 [INFO] gsuid_core.utils.download_resource.download_core | [GsCore资源下载]测速中... 
02-26 15:59:52 [SUCCESS] gsuid_core.server | 插件GenshinUID导入成功! 
02-26 15:59:52 [INFO] gsuid_core.utils.download_resource.download_core | [HKFRP] http://hk-1.5gbps-2.lcf.icu:10200 超时... 
02-26 15:59:52 [SUCCESS] gsuid_core.server | 插件core_command导入成功! 
02-26 15:59:53 [INFO] logging | Started server process [56132] 
02-26 15:59:53 [INFO] logging | Waiting for application startup. 
2024-02-26 15:59:53.404 | ERROR    | gsuid_core.web_app:lifespan:45 - the greenlet library is required to use this function. No module named 'greenlet'
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/cain/gsuid_core/gsuid_core/core.py", line 74, in main
    uvicorn.run(
    │       └ <function run at 0x101443b00>
    └ <module 'uvicorn' from '/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicorn/__init__.py'>

  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
    server.run()
    │      └ <function Server.run at 0x1014b1260>
    └ <uvicorn.server.Server object at 0x12387dc40>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x1014b1300>
           │       │   └ <uvicorn.server.Server object at 0x12387dc40>
           │       └ <function run at 0x1011468e0>
           └ <module 'asyncio' from '/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python...

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x123a12c40>
           │      └ <function Runner.run at 0x1011dbec0>
           └ <asyncio.runners.Runner object at 0x123a2a120>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-19' coro=<Server.serve() running at /Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicor...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x1011d9b20>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x123a2a120>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1011d9a80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1011db880>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10112dd00>
    └ <Handle Task.task_wakeup(<_GatheringFu... 'greenlet'")>)>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu... 'greenlet'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu... 'greenlet'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu... 'greenlet'")>)>

  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 86, in main
    await app(scope, self.receive, self.send)
          │   │      │    │        │    └ <function LifespanOn.send at 0x123ae9620>
          │   │      │    │        └ <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>
          │   │      │    └ <function LifespanOn.receive at 0x123ae96c0>
          │   │      └ <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>
          │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x123a414f0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
                 │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
                 │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
                 │    └ <fastapi.applications.FastAPI object at 0x10571ddc0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x123a414f0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
                           │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
                           └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x123acf6e0>
          └ <fastapi.applications.FastAPI object at 0x10571ddc0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x123acf680>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x123acf6e0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 103, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x123acf650>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x123acf680>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 48, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.routing.APIRouter object at 0x105704f50>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x123acf650>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x105704f50>>
          └ <fastapi.routing.APIRouter object at 0x105704f50>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/routing.py", line 767, in app
    await self.lifespan(scope, receive, send)
          │    │        │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │        │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x123a4e1b0>>
          │    │        └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <function Router.lifespan at 0x101f85800>
          └ <fastapi.routing.APIRouter object at 0x105704f50>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               │    │                └ <fastapi.applications.FastAPI object at 0x10571ddc0>
               │    └ <function lifespan at 0x105111da0>
               └ <fastapi.routing.APIRouter object at 0x105704f50>

> File "/Users/cain/gsuid_core/gsuid_core/web_app.py", line 43, in lifespan
    await asyncio.gather(*_task)
          │       │       └ [<coroutine object sr_adapter at 0x1232d6c30>, <coroutine object move_database at 0x123a99ff0>, <coroutine object load_global...
          │       └ <function gather at 0x1011d2520>
          └ <module 'asyncio' from '/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python...

  File "/Users/cain/gsuid_core/gsuid_core/utils/database/startup.py", line 35, in sr_adapter
    async with engine.begin() as conn:
               │      └ <function AsyncEngine.begin at 0x10428e020>
               └ <sqlalchemy.ext.asyncio.engine.AsyncEngine object at 0x10427ced0>

  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
                       │    └ <async_generator object AsyncEngine.begin at 0x123aeca90>
                       └ <contextlib._AsyncGeneratorContextManager object at 0x123a4f5c0>

  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1066, in begin
    async with conn:
               └ <sqlalchemy.ext.asyncio.engine.AsyncConnection object at 0x123adefd0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 125, in __aenter__
    return await self.start(is_ctxmanager=True)
                 │    └ <function AsyncConnection.start at 0x10427bba0>
                 └ <sqlalchemy.ext.asyncio.engine.AsyncConnection object at 0x123adefd0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
    await greenlet_spawn(self.sync_engine.connect)
          │              │    └ <member 'sync_engine' of 'AsyncConnection' objects>
          │              └ <sqlalchemy.ext.asyncio.engine.AsyncConnection object at 0x123adefd0>
          └ <function greenlet_spawn at 0x1037c71a0>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    _not_implemented()
    └ <function _not_implemented at 0x1037c6e80>
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 44, in _not_implemented
    raise ValueError(

ValueError: the greenlet library is required to use this function. No module named 'greenlet'
  File "/Users/cain/gsuid_core/gsuid_core/web_app.py", line 43, in lifespan
    await asyncio.gather(*_task)
  File "/Users/cain/gsuid_core/gsuid_core/utils/database/startup.py", line 35, in sr_adapter
    async with engine.begin() as conn:
  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1066, in begin
    async with conn:
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 125, in __aenter__
    return await self.start(is_ctxmanager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
    await greenlet_spawn(self.sync_engine.connect)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    _not_implemented()
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 44, in _not_implemented
    raise ValueError(
02-26 15:59:53 [INFO] gsuid_core.webconsole.__init__ | 尝试挂载WebConsole 
2024-02-26 15:59:53.477 | ERROR    | logging:callHandlers:1762 - Traceback (most recent call last):
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/gsuid_core/web_app.py", line 49, in lifespan
    await start_check()  # type:ignore
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/gsuid_core/webconsole/__init__.py", line 21, in start_check
    await site.db.async_run_sync(
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy_database/database.py", line 194, in run_sync
    async with self.engine.begin() as conn:
  File "/Users/cain/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1066, in begin
    async with conn:
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 125, in __aenter__
    return await self.start(is_ctxmanager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
    await greenlet_spawn(self.sync_engine.connect)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    _not_implemented()
  File "/Users/cain/gsuid_core/.venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 44, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

2024-02-26 15:59:53.477 | ERROR    | logging:callHandlers:1762 - Application startup failed. Exiting.
```

**Comment by KimigaiiWuyi** [comment]
安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`）
视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet`
安装`msvc-runtime`同理(`poetry run` or `pdm run`)

**Comment by CainLuo** [comment]
但是我本地是有 greenlet 这个库的:

```shell
➜  ~ pip3 list
Package    Version
---------- --------
certifi    2024.2.2
greenlet   3.0.3
meson      1.3.2
pip        24.0
setuptools 69.1.0
wheel      0.42.0
```

**Comment by KimigaiiWuyi** [comment]
> > 安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`） 视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet` 安装`msvc-runtime`同理(`poetry run` or `pdm run`)
> 
> @KimigaiiWuyi
> 
> 但是我本地是有 greenlet 这个库的:
> 
> ```shell
> ➜  ~ pip3 list
> Package    Version
> ---------- --------
> certifi    2024.2.2
> greenlet   3.0.3
> meson      1.3.2
> pip        24.0
> setuptools 69.1.0
> wheel      0.42.0
> ```

你使用的虚拟环境里面没有

**Comment by CainLuo** [comment]
> > > 安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`） 视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet` 安装`msvc-runtime`同理(`poetry run` or `pdm run`)
> > 
> > 
> > @KimigaiiWuyi
> > 但是我本地是有 greenlet 这个库的:
> > ```shell
> > ➜  ~ pip3 list
> > Package    Version
> > ---------- --------
> > certifi    2024.2.2
> > greenlet   3.0.3
> > meson      1.3.2
> > pip        24.0
> > setuptools 69.1.0
> > wheel      0.42.0
> > ```
> 
> 你使用的虚拟环境里面没有

唔....所以要怎么弄? 我的是 macOS

**Comment by KimigaiiWuyi** [comment]
> 安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`） 视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet` 安装`msvc-runtime`同理(`poetry run` or `pdm run`)

使用poetry的话就用`poetry run pip install greenlet` 然后再`poetry run core`
我已经给出了参考安装命令

**Comment by CainLuo** [comment]
> > 安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`） 视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet` 安装`msvc-runtime`同理(`poetry run` or `pdm run`)
> 
> 使用poetry的话就用`poetry run pip install greenlet` 然后再`poetry run core` 我已经给出了参考安装命令

ok, 谢谢, 那个 web 的账号密码在哪里可以看到?

**Comment by KimigaiiWuyi** [comment]
> > > 安装依赖`greenlet`（如果你是windows，还需要额外安装`msvc-runtime`） 视环境使用`poetry run pip install greenlet`或者`pip install greenlet`, 或者`pdm run pip install greenlet` 安装`msvc-runtime`同理(`poetry run` or `pdm run`)
> > 
> > 
> > 使用poetry的话就用`poetry run pip install greenlet` 然后再`poetry run core` 我已经给出了参考安装命令
> 
> ok, 谢谢, 那个 web 的账号密码在哪里可以看到?

文档有提到, 账密均为 root, 进入之后首先修改密码
