### ISSUE TITLE
【疑问】更新core之后重启加载starrailuid失败

### ISSUE THREAD

**Issue by mengluo04** [Genshin-bots/gsuid_core#72]
突然就报错了，删了sr的插件重新clone也是一样的
`
Warning: Found deprecated priority 'default' for source 'mirrors' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
08-30 22:41:13 [INFO] gsuid_core.server | [GsCore] 开始加载插件... 
08-30 22:41:13 [DEBUG] gsuid_core.server | 导入GenshinUID中... 
08-30 22:41:17 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_resource | [资源文件下载] 正在检查与下载缺失的资源文件，可能需要较长时间，请稍等 
08-30 22:41:17 [INFO] gsuid_core.utils.download_resource.download_core | [GsCore资源下载]测速中... 
08-30 22:41:17 [SUCCESS] gsuid_core.server | 插件GenshinUID导入成功! 
08-30 22:41:17 [DEBUG] gsuid_core.server | 导入StarRailUID中... 
2024-08-30 22:41:17.716 | ERROR    | gsuid_core.server:load_plugins:149 - 加载插件时发生错误: Expected `bool`, got `int` - at `$[...].data`
Traceback (most recent call last):

  File "/home/services/gsuid_core/gsuid_core/core.py", line 15, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/services/gsuid_core/gsuid_core/gss.py", line 12, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x7f12b39f2950>
    └ <gsuid_core.server.GsServer object at 0x7f12b7284460>

> File "/home/services/gsuid_core/gsuid_core/server.py", line 121, in load_plugins
    self.load_dir_plugins(path, True)
    │    │                └ PosixPath('/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID')
    │    └ <function GsServer.load_dir_plugins at 0x7f12b39f29e0>
    └ <gsuid_core.server.GsServer object at 0x7f12b7284460>

  File "/home/services/gsuid_core/gsuid_core/server.py", line 172, in load_dir_plugins
    importlib.import_module(f'{_p}')
    │         └ <function import_module at 0x7f12b69a6170>
    └ <module 'importlib' from '/usr/lib/python3.10/importlib/__init__.py'>

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.StarRailUID.StarRailUID.starrailuid_note'
           │          └ <function _gcd_import at 0x7f12b73af400>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_note/__init__.py", line 8, in <module>
    from ..utils.sr_prefix import PREFIX

  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/utils/sr_prefix.py", line 1, in <module>
    from ..starrailuid_config.sr_config import srconfig

  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_config/__init__.py", line 2, in <module>
    from ..starrailuid_config.sr_config import srconfig

  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_config/sr_config.py", line 6, in <module>
    srconfig = StringConfig(
               └ <class 'gsuid_core.utils.plugins_config.gs_config.StringConfig'>

  File "/home/services/gsuid_core/gsuid_core/utils/plugins_config/gs_config.py", line 56, in __init__
    self.update_config()
    │    └ <function StringConfig.update_config at 0x7f12b4c75240>
    └ <gsuid_core.utils.plugins_config.gs_config.StringConfig object at 0x7f12ab659570>

  File "/home/services/gsuid_core/gsuid_core/utils/plugins_config/gs_config.py", line 81, in update_config
    self.config: Dict[str, GSC] = msgjson.decode(
    │    │       │         │      │       └ <built-in function json_decode>
    │    │       │         │      └ <module 'msgspec.json' from '/root/.cache/pypoetry/virtualenvs/gsuid-core-K4LPybnJ-py3.10/lib/python3.10/site-packages/msgspe...
    │    │       │         └ typing.Union[gsuid_core.utils.plugins_config.models.GsDictConfig, gsuid_core.utils.plugins_config.models.GsBoolConfig, gsuid_...
    │    │       └ typing.Dict
    │    └ {}
    └ <gsuid_core.utils.plugins_config.gs_config.StringConfig object at 0x7f12ab659570>

msgspec.ValidationError: Expected `bool`, got `int` - at `$[...].data`
  File "/home/services/gsuid_core/gsuid_core/server.py", line 121, in load_plugins
    self.load_dir_plugins(path, True)
  File "/home/services/gsuid_core/gsuid_core/server.py", line 172, in load_dir_plugins
    importlib.import_module(f'{_p}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_note/__init__.py", line 8, in <module>
    from ..utils.sr_prefix import PREFIX
  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/utils/sr_prefix.py", line 1, in <module>
    from ..starrailuid_config.sr_config import srconfig
  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_config/__init__.py", line 2, in <module>
    from ..starrailuid_config.sr_config import srconfig
  File "/home/services/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_config/sr_config.py", line 6, in <module>
    srconfig = StringConfig(
  File "/home/services/gsuid_core/gsuid_core/utils/plugins_config/gs_config.py", line 56, in __init__
    self.update_config()
  File "/home/services/gsuid_core/gsuid_core/utils/plugins_config/gs_config.py", line 81, in update_config
    self.config: Dict[str, GSC] = msgjson.decode(
08-30 22:41:17 [WARNING] gsuid_core.server | 插件StarRailUID加载失败 
`

**Comment by KimigaiiWuyi** [comment]
在写入配置文件的时候被强制重启/关闭导致配置文件错误
请尝试检查并删除`\gsuid_core\data\StarRailUID\config.json`
重启即可自动生成配置文件

**Comment by mengluo04** [comment]
> 在写入配置文件的时候被强制重启/关闭导致配置文件错误 请尝试检查并删除`\gsuid_core\data\StarRailUID\config.json` 重启即可自动生成配置文件

删除后已解决，多谢
