### ISSUE TITLE
昨天更新后无法启动，报错如下

### ISSUE THREAD

**Issue by wzq10314** [Genshin-bots/gsuid_core#77]
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/root/gsuid_core/gsuid_core/core.py", line 10, in <module>

    from fastapi import WebSocket, WebSocketDisconnect

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>

    from .applications import FastAPI as FastAPI

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>

    from fastapi import routing

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 24, in <module>

    from fastapi import params

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/fastapi/params.py", line 5, in <module>

    from fastapi.openapi.models import Example

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/fastapi/openapi/models.py", line 246, in <module>

    class MediaType(BaseModelWithConfig):

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__

    complete_model_class(

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 577, in complete_model_class

    schema = cls.__get_pydantic_core_schema__(cls, handler)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 671, in __get_pydantic_core_schema__

    return handler(source)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__

    schema = self._handler(source_type)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema

    schema = self._generate_schema_inner(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner

    return self._model_schema(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema

    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 739, in <dictcomp>

    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema

    common_field = self._common_field_schema(name, field_info, decorators)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1308, in _common_field_schema

    schema = self._apply_annotations(

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations

    schema = get_inner_schema(source_type)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__

    schema = self._handler(source_type)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler

    schema = self._generate_schema_inner(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner

    return self.match_type(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type

    return self._match_generic_type(obj, origin)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type

    return self._union_schema(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema

    choices.append(self.generate_schema(arg))

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema

    schema = self._generate_schema_inner(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner

    return self.match_type(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type

    return self._match_generic_type(obj, origin)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1068, in _match_generic_type

    return self._dict_schema(*self._get_first_two_args_or_any(obj))

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 434, in _dict_schema

    return core_schema.dict_schema(self.generate_schema(keys_type), self.generate_schema(values_type))

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema

    schema = self._generate_schema_inner(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner

    return self.match_type(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type

    return self._match_generic_type(obj, origin)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type

    return self._union_schema(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema

    choices.append(self.generate_schema(arg))

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema

    schema = self._generate_schema_inner(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner

    return self.match_type(obj)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 999, in match_type

    return self._typed_dict_schema(obj, None)

  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1520, in _typed_dict_schema

    td_schema = core_schema.typed_dict_schema(

TypeError: typed_dict_schema() got an unexpected keyword argument 'cls'

**Comment by KimigaiiWuyi** [comment]
是使用的pdm吗，请使用
`pdm run python -m pip install pydantic==2.8.2 fastapi==0.109.2`
命令后尝试启动

**Comment by wzq10314** [comment]
> 是使用的pdm吗，请使用 `pdm run python -m pip install pydantic==2.8.2 fastapi==0.109.2` 命令后尝试启动

用的是poetry run core

**Comment by KimigaiiWuyi** [comment]
> > 是使用的pdm吗，请使用 `pdm run python -m pip install pydantic==2.8.2 fastapi==0.109.2` 命令后尝试启动
> 
> 用的是poetry run core

请使用
`poetry run pip install pydantic==2.8.2 fastapi==0.109.2`
如果不行，请执行`poetry run pip list`，然后截图结果

**Comment by wzq10314** [comment]
> > > 是使用的pdm吗，请使用 `pdm run python -m pip install pydantic==2.8.2 fastapi==0.109.2` 命令后尝试启动
> > 
> > 
> > 用的是poetry run core
> 
> 请使用 `poetry run pip install pydantic==2.8.2 fastapi==0.109.2` 如果不行，请执行`poetry run pip list`，然后截图结果

可以运行了 谢谢
