### ISSUE TITLE
初次启动后无法再启动

### ISSUE THREAD

**Issue by WorldHim** [Genshin-bots/gsuid_core#80]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/importlib/__init__.py",
line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/gsuid_core/gsuid_core/core.py", line 15, in <module>
    from gsuid_core.gss import gss  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gsuid_core/gsuid_core/gss.py", line 3, in <module>
    from gsuid_core.aps import scheduler
  File "/opt/gsuid_core/gsuid_core/aps.py", line 5, in <module>
    from gsuid_core.logger import logger
  File "/opt/gsuid_core/gsuid_core/logger.py", line 10, in <module>
    from gsuid_core.config import core_config
  File "/opt/gsuid_core/gsuid_core/config.py", line 129, in <module>
    core_config = CoreConfig()
                  ^^^^^^^^^^^^
  File "/opt/gsuid_core/gsuid_core/config.py", line 53, in __init__
    self.update_config()
  File "/opt/gsuid_core/gsuid_core/config.py", line 62, in update_config
    self.config: Dict[str, Any] = json.load(f)
     ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line
293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line
346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 17 column 28 (char 353
```

**Comment by KimigaiiWuyi** [comment]
config.json写入时强关导致的文件损坏
可以删除config.json再次启动重新生成
路径位于`gsuid_core/gsuid_core/config.json`
