### ISSUE TITLE
更新后无法启动

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Genshin-bots/gsuid_core#81]
报错如下
```Python
Traceback (most recent call last):
  File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\core.py", line 10, in <module>
    from fastapi import WebSocket, WebSocketDisconnect
  File "C:\Users\YuYue\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-YV938Htm-py3.10\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\YuYue\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-YV938Htm-py3.10\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
ImportError: cannot import name 'routing' from partially initialized module 'fastapi' (most likely due to a circular import) (C:\Users\YuYue\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-YV938Htm-py3.10\lib\site-packages\fastapi\__init__.py)
```

**Comment by KimigaiiWuyi** [comment]
请截图fastapi和pydantic依赖版本

**Comment by YuYue-Amatsuki** [comment]
> 请截图fastapi和pydantic依赖版本

![image](https://github.com/user-attachments/assets/07cef851-a492-4d6e-adae-4b6c4f3cd4b3)

**Comment by KimigaiiWuyi** [comment]
请尝试重新安装fastapi
 
`poetry run pip uninstall fastapi`
`poetry run pip install fastapi==0.112.2`

**Comment by YuYue-Amatsuki** [comment]
> 请尝试重新安装fastapi
>  
> `poetry run pip uninstall fastapi`
> `poetry run pip install fastapi==0.112.2`

感谢，已解决
